apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
          readOnly: true
        - name: nginx-configs
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
      - name: www-data
        persistentVolumeClaim:
          claimName: www-data
      - name: nginx-configs
        configMap:
          name: nginx.conf.d