apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  type: NodePort
  ports:
  - port: 9001
    nodePort: 30008
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - port: 9000
  selector:
    app: minio