apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:6.5-apache
    ports:
    - containerPort: 80
    volumeMounts:
    - name: www-data
      mountPath: /var/www/html
    env:
      - name: WORDPRESS_DB_HOST
        value: 127.0.0.1
      - name: WORDPRESS_DB_USER
        value: wordpress
      - name: WORDPRESS_DB_NAME
        value: wordpress
      - name: WORDPRESS_DB_PASSWORD
        value: secret

  - name: mariadb
    image: mariadb:10.11
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mariadb
      mountPath: /var/lib/mysql
    env:
    - name: MARIADB_DATABASE
      value: wordpress
    - name: MARIADB_USER
      value: wordpress
    - name: MARIADB_PASSWORD
      value: secret
    - name: MARIADB_RANDOM_ROOT_PASSWORD
      value: verysecret

  volumes:
  - name: www-data
    persistentVolumeClaim:
      claimName: www-data
  - name: mariadb
    persistentVolumeClaim:
      claimName: mariadb
